version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - call dev_scripts\install_dependencies.cmd
  - call dev_scripts\build_game.cmd
  - call dev_scripts\package_game.cmd

artifacts:
- path: dev_scripts\DIST\controlz_demo_linux.tar.gz
  name: controlz_demo_linux.tar.gz
- path: dev_scripts\DIST\controlz_demo_windows.zip
  name: controlz_demo_windows.zip
- path: dev_scripts\DIST\controlz.scm
  name: controlz.scm
- path: package.json
  name: package.json
  
deploy:
- provider: GitHub
  auth_token:
    secure: s4GYQwPs7midYlucoxO2HdJGjYxJCf9xEp9fakfJljeGu4JWRxhiA043fIdUmxRCXBspnBqubH5xFTY6ZeBKKbjRwMlE2MUc6vb6Yc6vK/5n8fydG4CHVF5wRvFjFsgH
  artifact: controlz.scm, controlz_demo_linux.tar.gz, controlz_demo_windows.zip, package.json
  draft: false
  prerelease: false
  force_update: true          # it can't edit a release artifact if this is false
  on:
    branch: main              # release from main branch only
    appveyor_repo_tag: true   # deploy on tag push only
